# Generated by Django 3.2.19 on 2023-05-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
                ('agreement', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, max_length=255)),
            ],
        ),
    ]
